package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"

	"github.com/techvifyharrydo/Room-Reservation/ent"
	graphql1 "github.com/techvifyharrydo/Room-Reservation/graphql"
)

// ID is the resolver for the id field.
func (r *officeResolver) ID(ctx context.Context, obj *ent.Office) (string, error) {
	return obj.ID.String(), nil
}

// Office returns graphql1.OfficeResolver implementation.
func (r *Resolver) Office() graphql1.OfficeResolver { return &officeResolver{r} }

type officeResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *officeResolver) Rooms(ctx context.Context, obj *ent.Office) ([]*ent.Room, error) {
	return obj.QueryRooms().All(ctx)
}
