// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookingsColumns holds the columns for the "bookings" table.
	BookingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "is_repeat", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "office_id", Type: field.TypeUUID},
		{Name: "room_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// BookingsTable holds the schema information for the "bookings" table.
	BookingsTable = &schema.Table{
		Name:       "bookings",
		Columns:    BookingsColumns,
		PrimaryKey: []*schema.Column{BookingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bookings_offices_bookings",
				Columns:    []*schema.Column{BookingsColumns[5]},
				RefColumns: []*schema.Column{OfficesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "bookings_rooms_bookings",
				Columns:    []*schema.Column{BookingsColumns[6]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "bookings_users_bookings",
				Columns:    []*schema.Column{BookingsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OfficesColumns holds the columns for the "offices" table.
	OfficesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// OfficesTable holds the schema information for the "offices" table.
	OfficesTable = &schema.Table{
		Name:       "offices",
		Columns:    OfficesColumns,
		PrimaryKey: []*schema.Column{OfficesColumns[0]},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "color", Type: field.TypeString, Size: 7},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "office_id", Type: field.TypeUUID},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rooms_offices_rooms",
				Columns:    []*schema.Column{RoomsColumns[5]},
				RefColumns: []*schema.Column{OfficesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "work_email", Type: field.TypeString, Size: 255},
		{Name: "oid", Type: field.TypeString, Unique: true, Size: 255},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookingsTable,
		OfficesTable,
		RoomsTable,
		UsersTable,
	}
)

func init() {
	BookingsTable.ForeignKeys[0].RefTable = OfficesTable
	BookingsTable.ForeignKeys[1].RefTable = RoomsTable
	BookingsTable.ForeignKeys[2].RefTable = UsersTable
	RoomsTable.ForeignKeys[0].RefTable = OfficesTable
}
