// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

import (
	"time"
)

type AuthenticationToken struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	TokenType    string    `json:"tokenType"`
	ExpiresAt    time.Time `json:"expiresAt"`
	Email        string    `json:"email"`
}

type BookingData struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	StartDate string  `json:"startDate"`
	StartTime string  `json:"startTime"`
	EndTime   string  `json:"endTime"`
	IsRepeat  *bool   `json:"isRepeat,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	Office    *Office `json:"office"`
	Room      *Room   `json:"room"`
	User      *User   `json:"user"`
}

type BookingFilter struct {
	From     string  `json:"from"`
	To       string  `json:"to"`
	OfficeID string  `json:"officeId"`
	RoomID   *string `json:"roomId,omitempty"`
}

type BookingResponse struct {
	Message string       `json:"message"`
	Data    *BookingData `json:"data"`
}

type CreateBookingInput struct {
	Title     string  `json:"title"`
	StartDate string  `json:"startDate"`
	StartTime string  `json:"startTime"`
	EndTime   string  `json:"endTime"`
	IsRepeat  *bool   `json:"isRepeat,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	OfficeID  string  `json:"officeId"`
	RoomID    string  `json:"roomId"`
	UserID    string  `json:"userId"`
}

type CreateOfficeInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateRoomInput struct {
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	OfficeID    string  `json:"officeId"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}

type GetAvailableRoomInput struct {
	StartDate string  `json:"startDate"`
	StartTime string  `json:"startTime"`
	EndTime   string  `json:"endTime"`
	IsRepeat  *bool   `json:"isRepeat,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	OfficeID  string  `json:"officeId"`
}

type OfficeDto struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Rooms       []*Room `json:"rooms"`
}

type OfficeResponse struct {
	Message string  `json:"message"`
	Data    *Office `json:"data"`
}

type RoomFilter struct {
	OfficeID string `json:"officeId"`
}

type RoomResponse struct {
	Message string `json:"message"`
	Data    *Room  `json:"data"`
}

type UpdateBookingInput struct {
	ID        string  `json:"id"`
	Title     *string `json:"title,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
	IsRepeat  *bool   `json:"isRepeat,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	OfficeID  *string `json:"officeId,omitempty"`
	RoomID    *string `json:"roomId,omitempty"`
	UserID    *string `json:"userId,omitempty"`
}

type UpdateOfficeInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateRoomInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Color       *string `json:"color,omitempty"`
	OfficeID    *string `json:"officeId,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}
