// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (n *News) AuthorEdge(ctx context.Context) (*User, error) {
	result, err := n.Edges.AuthorEdgeOrErr()
	if IsNotLoaded(err) {
		result, err = n.QueryAuthorEdge().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) NewsEdges(ctx context.Context) (result []*News, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedNewsEdges(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.NewsEdgesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryNewsEdges().All(ctx)
	}
	return result, err
}
