// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/techvifyharrydo/Room-Reservation/ent/booking"
	"github.com/techvifyharrydo/Room-Reservation/ent/office"
	"github.com/techvifyharrydo/Room-Reservation/ent/room"
	"github.com/techvifyharrydo/Room-Reservation/ent/schema"
	"github.com/techvifyharrydo/Room-Reservation/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookingFields := schema.Booking{}.Fields()
	_ = bookingFields
	// bookingDescTitle is the schema descriptor for title field.
	bookingDescTitle := bookingFields[1].Descriptor()
	// booking.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	booking.TitleValidator = func() func(string) error {
		validators := bookingDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookingDescIsRepeat is the schema descriptor for is_repeat field.
	bookingDescIsRepeat := bookingFields[4].Descriptor()
	// booking.DefaultIsRepeat holds the default value on creation for the is_repeat field.
	booking.DefaultIsRepeat = bookingDescIsRepeat.Default.(bool)
	// bookingDescID is the schema descriptor for id field.
	bookingDescID := bookingFields[0].Descriptor()
	// booking.DefaultID holds the default value on creation for the id field.
	booking.DefaultID = bookingDescID.Default.(func() uuid.UUID)
	officeFields := schema.Office{}.Fields()
	_ = officeFields
	// officeDescName is the schema descriptor for name field.
	officeDescName := officeFields[1].Descriptor()
	// office.NameValidator is a validator for the "name" field. It is called by the builders before save.
	office.NameValidator = func() func(string) error {
		validators := officeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// officeDescID is the schema descriptor for id field.
	officeDescID := officeFields[0].Descriptor()
	// office.DefaultID holds the default value on creation for the id field.
	office.DefaultID = officeDescID.Default.(func() uuid.UUID)
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[1].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = func() func(string) error {
		validators := roomDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roomDescColor is the schema descriptor for color field.
	roomDescColor := roomFields[2].Descriptor()
	// room.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	room.ColorValidator = func() func(string) error {
		validators := roomDescColor.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
			validators[3].(func(string) error),
		}
		return func(color string) error {
			for _, fn := range fns {
				if err := fn(color); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roomDescID is the schema descriptor for id field.
	roomDescID := roomFields[0].Descriptor()
	// room.DefaultID holds the default value on creation for the id field.
	room.DefaultID = roomDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescWorkEmail is the schema descriptor for work_email field.
	userDescWorkEmail := userFields[2].Descriptor()
	// user.WorkEmailValidator is a validator for the "work_email" field. It is called by the builders before save.
	user.WorkEmailValidator = userDescWorkEmail.Validators[0].(func(string) error)
	// userDescOid is the schema descriptor for oid field.
	userDescOid := userFields[3].Descriptor()
	// user.OidValidator is a validator for the "oid" field. It is called by the builders before save.
	user.OidValidator = userDescOid.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
